// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateEarningsParams struct {
	Amount     pgtype.Numeric
	DateOfWork pgtype.Date
	PayrollID  int64
	WorkerID   int64
	CrewID     pgtype.Int8
}

type CreatePayrollsParams struct {
	PayPeriod   PayrollPayPeriod
	PeriodStart pgtype.Date
	PeriodEnd   pgtype.Date
}

type CreateWorkersParams struct {
	FirstName string
	LastName  string
}
